[package]
name = "databento"
authors = ["Databento <support@databento.com>"]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/databento/databento-rs"
description = "Official Databento client library"
license = "Apache-2.0"
# maximum of 5
keywords = ["real-time", "historical", "market-data", "trading", "tick-data"]
# see https://crates.io/category_slugs
categories = ["api-bindings", "finance"]

[features]
default = ["historical", "live"]
historical = ["dep:base64", "dep:reqwest", "dep:serde", "dep:serde_json", "time/serde"]
live = ["dep:hex", "dep:sha2"]

[dependencies]
# Historical auth
base64 = { version = "0.21.2", optional = true }
# binary encoding
dbn = { path = "../dbn/rust/dbn", features = ["async", "serde"] }
# Hex encoding used for Live authentication
hex = { version = "0.4", optional = true }
# Logging
log = "0.4"
# HTTP client for historical API
reqwest = { version = "0.11", optional = true, features = ["json"] }
# JSON deserialization for historical API
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_json = { version = "1.0", optional = true }
# Used for Live authentication
sha2 = { version = "0.10", optional = true }
# Error handling
thiserror = "1.0.40"
# Dates and datetimes
time = "0.3"
# Async run time
tokio = { version = "1.27", features = ["net"] }
# Builders for method parameters
typed-builder = { version = "0.14" }
